name: build and upload

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        os: [ubuntu-latest, macos-12, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    - name: set up conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        conda install -c conda-forge twine
        conda install -c conda-forge wheel
        conda install -c conda-forge setuptools
        conda install -c conda-forge pip
        conda install -c conda-forge gsl
        conda install -c conda-forge pycifrw
        conda install -c conda-forge six
        conda install -c conda-forge diffpy.structure

    - name: Build wheels
      run: |
        python setup.py sdist bdist_wheel

    - name: Run tests
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge numpy
        python setup.py install
        python conda-recipe/run_test.py

    - name: Upload Artifacts GitHub releases
      uses: ncipollo/release-action@v1
      with:
        draft: false
        prerelease: true
        allowUpdates: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ github.workspace }}/dist/*.whl
        tag: 0.0.1
        body: This is an alpha build of the pdffit2 library (0.0.1)

    - name: Checkout target repo
      uses: actions/checkout@v4
      env:
        REPO: easyScience/pypi
        REPO_PATH: pypi
      with:
        fetch-depth: 0
        token: ${{ secrets.ES_TOKEN }}
        repository: ${{ env.REPO }}
        path: ${{ env.REPO_PATH }}
        ref: "master"  # temporarily, switch branch from master

